config/routes.rb
Rails.application.routes.draw do
  root 'contacts#index'

  resources :contacts do
    collection do
      post :import
      get :export
    end

    member do
      get :share
    end
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  has_many :phones
  has_many :emails

  validates :first_name, :last_name, :full_name, :emails, :phones, presence: true
  validates :full_name, uniqueness: true

  before_validation :set_full_name

  accepts_nested_attributes_for :phones, allow_destroy: true
  accepts_nested_attributes_for :emails, allow_destroy: true

  def phones_list
    phones.map(&:phone)
  end

  def emails_list
    emails.map(&:email)
  end

  private

  def set_full_name
    self.full_name = "#{first_name} #{last_name}"
  end
end

app/models/email.rb
class Email < ActiveRecord::Base
  belongs_to :contact

  validates :email, presence: true
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :contact

  validates :phone, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    load_contacts
  end

  def show
    load_contact
  end

  def new
    build_contact
  end

  def create
    build_contact
    save_contact || render('new')
  end

  def edit
    load_contact
    build_contact
  end

  def update
    load_contact
    build_contact
    save_contact || render('edit')
  end

  def destroy
    load_contact
    @contact.destroy
    redirect_to contacts_path
  end

  def import
    return redirect_to contacts_path, alert: t('.blank') if params[:file].blank?
    import_file
    if @errors.present?
      load_contacts
      render :index
    else
      redirect_to contacts_path, notice: t('.success')
    end
  end

  def export
    filename = Contact::ExportCSV.perform(Contact.includes(:emails, :phones))
    send_file(filename, filename: 'contacts.csv', type: 'application/csv')
  end

  def share
    load_contact
    share_contact
  end

  private

  def import_file
    @errors = Contact::ImportCSV.perform(params[:file].tempfile)
  end

  def share_contact
    ContactMailer.share(@contact, params[:mail_to]).deliver_now if params[:mail_to].blank?
    redirect_to @contact, notice: params[:mail_to].present? ? t('.success') : t('.failed')
  end

  def load_contacts
    @contacts ||= contact_scope.to_a
  end

  def load_contact
    @contact ||= contact_scope.find(params[:id])
  end

  def build_contact
    @contact ||= contact_scope.build
    @contact.attributes = contact_params
  end

  def save_contact
    redirect_to @contact if @contact.save
  end

  def contact_params
    contact_params = params[:contact]
    if contact_params
      contact_params.permit(
        :first_name, :last_name,
        phones_attributes: [:id, :phone, :_destroy],
        emails_attributes: [:id, :email, :_destroy]
      )
    else
      {}
    end
  end

  def contact_scope
    Contact.order('lower(last_name)')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
  def view_errors(errors)
    html = ''
    if errors.is_a? ActiveModel::Errors
      errors.each do |_, msg|
        html << content_tag(:p, "#{msg}")
      end
    else
      Array.wrap(errors).each do |error|
        html << content_tag(:p, error)
      end
    end
    html.html_safe
  end

  def messages(messages)
    html = ''
    messages.each do |name, msg|
      next if !msg.is_a?(String) && msg.blank? && name.blank?
      html << content_tag(:div, msg, id: "flash_#{name}")
    end
    html.html_safe
  end
end

app/views/contacts/_contact.html.slim
tr
  td= link_to contact.full_name, contact_path(contact)

app/views/contacts/_errors.html.slim
- if @errors || @contact.try(:errors).present?
  #errors
    = view_errors(@errors || @contact.try(:errors))

app/views/contacts/_form.html.slim
= render 'errors'

.actions
  p.left = link_to t('contacts.back'), @contact

.show
  = nested_form_for(@contact, id: 'contact-form') do |f|
    p.text-left
      = f.label :first_name
      br = f.text_field :first_name, placeholder: :first_name
    p.text-left
      = f.label :last_name
      br = f.text_field :last_name, placeholder: :last_name

    div.form-contacts
      .left
        = f.label :emails
        = f.fields_for :emails do |email_form|
          = email_form.text_field :email, type: :email, placeholder: :email
          = email_form.link_to_remove '[x]'
        div = f.link_to_add t('contacts.add'), :emails
    div.form-contacts
      .left
        = f.label :phones
        = f.fields_for :phones do |phone_form|
          = phone_form.text_field :phone, type: :phone, placeholder: :phone
          = phone_form.link_to_remove '[x]'
        div = f.link_to_add t('contacts.add'), :phones
    div.show-footer
      .left
        = f.submit

app/views/contacts/_import_form.html.slim
= form_tag import_contacts_path, multipart: true do
  = file_field_tag :file, accept: 'text/csv'
  = submit_tag t('contacts.index.import')

app/views/contacts/edit.html.slim
= render 'form'

app/views/contacts/index.html.slim
= render 'errors'

.table-wrapper
  .table-scroll
    table
      thead
        tr
          th
            h3#contacts = t('.title')
            h3#add = link_to t('.add'), new_contact_path
      tfoot
        tr
          th
            h3#contacts = render 'import_form'
            h3#add = button_to t('.export'), export_contacts_path, method: :get
      tbody
        = render partial: 'contact', collection: @contacts

app/views/contacts/new.html.slim
= render 'form'

app/views/contacts/show.html.slim
.actions
  p.left = link_to t('contacts.back'), contacts_path

.show
  h3 = @contact.full_name
  div.contacts
    .left
      ul#contacts-block = t('.phones')
      - @contact.phones_list.each do |phone|
        li = phone

    .right
      ul.text-right = t('.emails')
      - @contact.emails_list.each do |email|
        li.text-right = link_to email, "mailto:#{email}"

  div.show-footer
    .left
      = form_tag share_contact_path(@contact), method: :get do
        = text_field_tag :mail_to, '', placeholder: 'user@example.com'
        = submit_tag t('.share')
    .right
      = button_to t('.delete'), contact_path(@contact), method: :delete, data: { confirm: t('.delete_confirm') }
    .right = button_to t('.edit'), edit_contact_path(@contact), method: :get

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Small Address Book
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = messages(flash)

    = yield